README.md, packages/nx-go/src/builders/serve/builder.spec.ts, packages/nx-go/src/builders/serve/builder.ts, packages/nx-go/src/builders/serve/schema.d.ts, packages/nx-go/src/utils/go-utils.ts
This PR adds support for overriding the `go` binary in the `serve` builder. This allows for running the application in watch mode when using a tool like [gow](https://github.com/mitranim/gow).
=> feat: add option cmd to serve builder to allow overriding the go binary

e2e/nx-go-e2e/tests/nx-go.spec.ts, e2e/nx-go-e2e/utils/folder.ts, packages/nx-go/generators.json, packages/nx-go/src/generators/setup-nx-go-plugin/generator.spec.ts, packages/nx-go/src/generators/setup-nx-go-plugin/generator.ts, packages/nx-go/src/generators/setup-nx-go-plugin/schema.d.ts, packages/nx-go/src/generators/setup-nx-go-plugin/schema.json, packages/nx-go/src/go-package-graph/index.ts, packages/nx-go/src/index.ts
Implements the graph plugin so that go projects can properly relate to each other in the Nx workspace.
Currently added a generator to setup the plugin so that users can opt-in. We can execute the generator logic when application or library generators are executed if we want to for an automatic approach.
Will add e2e testing to make sure the graph logic behaves correctly but wanted to create the request to start the review.
Closes #14.
=> Add package graph support

packages/nx-go/src/go-package-graph/index.ts, packages/nx-go/src/utils/find-workspace-root-path.ts
Currently when the plugin runs from within the daemon that Nx runs to efficiently process changes to the dependency graph the plugin will throw an error like so in `node_modules/.cache/nx/d/daemon.log`:
```
stat /path/to/workspace/node_modules/.pnpm/@nrwl+workspace@13.8.1_95b412ae97cf96e9f43494b4913c978e/node_modules/@nrwl/workspace/src/core/project-graph/daemon/client/apps/api/main.go: directory not found
Error: Command failed: go list -json ./apps/api/main.go
stat /path/to/workspace/node_modules/.pnpm/@nrwl+workspace@13.8.1_95b412ae97cf96e9f43494b4913c978e/node_modules/@nrwl/workspace/src/core/project-graph/daemon/client/apps/api/main.go: directory not found
at checkExecSyncError (node:child_process:828:11)
at execSync (node:child_process:902:15)
at getGoDependencies …
```
=> Fixed command failed when running in graph daemon

packages/nx-go/src/executors/build/executor.spec.ts, packages/nx-go/src/executors/lint/executor.spec.ts, packages/nx-go/src/executors/serve/executor.spec.ts, packages/nx-go/src/executors/test/executor.spec.ts
We mock the `runGoCommand` to assert that the correct function is being called.
I used the source in https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.spec.ts#L37 to see how to mock the use of a function from a separate module.
Next step would be to have tests to validate the correct go command is being executed based on the inputs.
=> Fixed executor unit tests to at least pass

packages/nx-go/src/executors/build/executor.ts
Fix for #55.
Appends **.exe** extension to `options.outputPath` if `process.platform` is **win32** else leave untouched.
=> fix: missing .exe extension of executable on windows

packages/nx-go/migrations.json, packages/nx-go/package.json, packages/nx-go/project.json, packages/nx-go/src/generators/application/generator.spec.ts, packages/nx-go/src/migrations/add-go-mod-to-implicit-deps/add-go-mod-to-implicit-deps.ts, packages/nx-go/src/utils/create-go-mod.helper.ts, packages/nx-go/src/utils/ensureGoModDependency.ts
If the application generator is executed and the `skipGoMod` is undefined or false then we will ensure that `go.mod: "*"` is added to `implicitDependencies` in `nx.json`.
Added a migration for 2.3.0 so that when users upgrade their workspace it will add the dependency if `go.mod` exists.
Closes #52.
=> Updated Application generator to ensure go.mod is added to implicit dependencies

packages/nx-go/src/executors/serve/executor.spec.ts, packages/nx-go/src/executors/serve/executor.ts, packages/nx-go/src/executors/serve/schema.d.ts, packages/nx-go/src/executors/serve/schema.json
This feature enables users to specify extra command line arguments for the `serve` target. Beyond just `go run main.go`, we can now have invocations of the form `go run main.go subcommand -flag --double-dash-option` (as an example).
This PR also brings the `serve` executor's JSON schema in sync with its TypeScript definition. Additionally, it removes the `outputPath` field from the schema, which was not being used by this target (as there is no build output when running the application).
=> Enable command line arguments for serve target

.github/workflows/run-e2e.yml, packages/nx-go/src/go-package-graph/index.ts
Hello everyone. I know that @phillipCouto is working on this, but I found the fix a couple of days ago, but didn't have time to push it to Github. 
I think the problem is actually in Go 1.18 as it returns null for the Module, in go list -json file, as for whatever reason. So the go list -m -json should return the information we seek for now.
=> fix: dep graph working with go 1.18

packages/nx-go/src/go-package-graph/index.ts
Closes #66 
Reworked the dependency graph plugin to properly support the streaming json format from `go list -m`. Also fixed the logic to match up go imports to Nx project names.
The logic of matching a go import to an Nx project is as follows:
1. Find the go module with the closest path to the go import
2. Extract the relative path for the import from the selected go module (import may be a folder in a module)
3. Extract the relative directory path for the module in the Nx workspace
4. Apply the relative path from step 2 onto the directory path from step 3
5. Look up the project name using the relative path
6. If no project name is found then set relative path to one folder up and go back to step 5
7. Repeat steps 5 and 6 until a project name is found or we reach `.` which means we are …
=> Reworked the dependency graph plugin to properly support go workspaces

README.md
Added details to the README on how to enable the nx-go plugin so go packages can be linked together in the dependency graph automatically.
=> Updated README with details on enabling nx-go plugin

packages/nx-go/src/executors/build/executor.spec.ts, packages/nx-go/src/executors/build/executor.ts, packages/nx-go/src/executors/build/schema.d.ts, packages/nx-go/src/executors/build/schema.json, packages/nx-go/src/utils/run-go-command.helper.ts
A few enhancements:
1. Added OS interoperable way of passing environment variables to go build
2. Added ability to pass build flags to build executor
3. Updated executor schema to properly communicate the options and expected types
4. Expanded unit tests to validate new functionality
5. Updated executor options to properly communicate output and main are optional  
This replaces the PR #65
=> feat: pass flags and environment variables to go build

packages/nx-go/migrations.json, packages/nx-go/src/executors/build/schema.json, packages/nx-go/src/executors/lint/schema.json, packages/nx-go/src/executors/serve/schema.json, packages/nx-go/src/executors/test/schema.json, packages/nx-go/src/migrations/update-3.0.0/update-executors-options.spec.ts, packages/nx-go/src/migrations/update-3.0.0/update-executors-options.ts
As mentioned in #107, 3.0.0-beta.0 is missing a migration for a smooth transition of executor options. This migration will change the following options:
- **@nx-go/nx-go:lint**: transform `args` option to an array of strings
- **@nx-go/nx-go:serve**: rename option `arguments` to `args`
I hope I haven't forgotten any of the options affected.
🚀 This change will be available in the next beta version!
=> Add migration for executors options

.github/workflows/ci.yml, .github/workflows/sonar.yml
We can see in #111 that the Sonar analysis cannot be performed in PR from forks. So I propose to have an additional workflow that is executed from the main branch (to remain secure). It is configured to run just after the build workflow. It launches the Sonarcloud action with the coverage generated before.
=> Add support for fork-based Sonar analysis

docs/executors/test.md, packages/nx-go-e2e/src/nx-go.spec.ts, packages/nx-go/src/executors/test/executor.spec.ts, packages/nx-go/src/executors/test/executor.ts, packages/nx-go/src/executors/test/schema.d.ts, packages/nx-go/src/executors/test/schema.json, packages/nx-go/src/migrations/update-3.0.0/update-executors-options.spec.ts, packages/nx-go/src/migrations/update-3.0.0/update-executors-options.ts
In large test suites, verbose test output can make it difficult to pinpoint failing tests.
This PR adds an option to the test executor to disable verbose test output. It defaults to "true" for backward compatibility.
=> Option to disable verbose test output

docs/executors/test.md, packages/nx-go/src/executors/test/executor.spec.ts, packages/nx-go/src/executors/test/executor.ts, packages/nx-go/src/executors/test/schema.d.ts, packages/nx-go/src/executors/test/schema.json
This PR adds the "coverProfile" property to the test executor, in order to save the cover in a file (as described [here](https://pkg.go.dev/cmd/go/internal/test) in the Go documentation).
Closes #45
=> Add coverProfile to test executor

docs/executors/test.md, packages/nx-go-e2e/shared/create-test-project.ts, packages/nx-go-e2e/src/nx-go.spec.ts, packages/nx-go/src/executors/test/executor.spec.ts, packages/nx-go/src/executors/test/executor.ts, packages/nx-go/src/executors/test/schema.d.ts, packages/nx-go/src/executors/test/schema.json
This PR adds the "run" property to the test executor, in order to only run tests matching a specified regular expression (as described [here](https://pkg.go.dev/cmd/go/internal/test) in the Go documentation).
Closes #90
=> Add run property to test executor

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, packages/nx-go/package.json
This PR adds the support of **Nx 19**. This major update does not appear to have any impact on the nx-go plugin. I've run few successful migrations. Please let me know of any problems with Nx 19 (apart from the peer dependency issue).
Note that we'll need to take an interest in [Project Crystal](https://nx.dev/concepts/inferred-tasks), as it will simplify Nx project configuration.
=> Add support of Nx 19

packages/nx-go-e2e/src/nx-go.spec.ts, packages/nx-go/src/generators/application/generator.spec.ts, packages/nx-go/src/generators/application/generator.ts, packages/nx-go/src/generators/library/generator.spec.ts, packages/nx-go/src/generators/library/generator.ts, packages/nx-go/src/utils/normalize-options.spec.ts, packages/nx-go/src/utils/normalize-options.ts
This PR modifies the project names used in the generators to improve the Go module and package names in the generated files.
Resolves #118
=> Do not strip away special characters from project names

README.md, docs/executors/generate.md, packages/nx-go-e2e/shared/update-nx-config.ts, packages/nx-go-e2e/src/nx-go.spec.ts, packages/nx-go/executors.json, packages/nx-go/migrations.json, packages/nx-go/src/executors/generate/executor.spec.ts, packages/nx-go/src/executors/generate/executor.ts, packages/nx-go/src/executors/generate/schema.d.ts, packages/nx-go/src/executors/generate/schema.json, packages/nx-go/src/migrations/update-3.2.0/replace-run-commands-with-generate-executor.spec.ts, packages/nx-go/src/migrations/update-3.2.0/replace-run-commands-with-generate-executor.ts
I propose to add a "generate" executor which will execute the `go generate` command inside a Nx project.
Not all developers use this Golang feature, so I haven't added it to **nx-go** generators.
I'll probably add an automatic migration for users who use it via a `run-command` today!
Resolve #53
=> Add a generate executor

docs/executors/build.md, packages/nx-go/src/executors/build/executor.spec.ts, packages/nx-go/src/executors/build/executor.ts, packages/nx-go/src/executors/build/schema.d.ts, packages/nx-go/src/executors/build/schema.json, packages/nx-go/src/executors/test/executor.spec.ts, packages/nx-go/src/executors/test/executor.ts, packages/nx-go/src/utils/execute-command.spec.ts, packages/nx-go/src/utils/execute-command.ts
This PR adds the "buildMode" property to the build executor, in order to indicate which kind of object file is to be built (as described [here](https://pkg.go.dev/cmd/go#hdr-Build_modes) in the Go documentation).
Closes #43
=> feat: add buildMode property to build executor

.github/actions/setup/action.yml, .gitignore, .prettierignore, package.json
I've found out that **Nx 17.x** is not compatible with **pnpm v9**.
But as the version is not frozen in the package.json file, it installed version 9 on my computer and nothing worked. To avoid any error until #137 is merged, I have explicitly set the pnpm version in the `package.json` file.
=> chore: stick pnpm version to v8

docs/executors/build.md, packages/nx-go/src/executors/build/executor.spec.ts, packages/nx-go/src/executors/build/executor.ts, packages/nx-go/src/executors/build/schema.d.ts, packages/nx-go/src/executors/build/schema.json
This supports a different command (like using tinygo instead of go) for the build target.
Fixes #93
=> support tinygo

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, packages/nx-go/package.json
This PR includes updates to various configuration files to support newer versions of Go and Node.js, as well as updates to compatibility information for `nx-go` with Nx.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL15-R16): Updated Go version to `1.23.2` and Node.js version to `22.x` in the matrix strategy and setup steps. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL15-R16) [[2]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL44-R45)
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L20-R21): Updated Go version to `1.23.2` and Node.js version to `22.x` in the setup steps.
* …
=> Add support of Nx 20

README.md, docs/options.md, packages/nx-go/src/graph/create-dependencies.spec.ts, packages/nx-go/src/graph/create-dependencies.ts, packages/nx-go/src/type.d.ts, packages/nx-go/src/utils/go-bridge.spec.ts, packages/nx-go/src/utils/go-bridge.ts
This PR adds a global option to the plugin called `skipGoDependencyCheck` in order to use the plugin without Go installed on your machine. This is a solution to avoid all members collaborating on the same monorepo having to install the Golang stack, if they are only working on other projects in the workspace.
> [!WARNING]
> Please be aware that if Go is not installed, the plugin will not be able to detect dependencies between Go projects and this is source of misunderstanding. So use this option with the utmost caution.
↪️ What do you think of the name of the option `skipGoDependencyCheck`?
In `nx.json` file, you can pass an object with options when adding `@nx-go/nx-go` plugin.
```json
{
"$schema": "./node_modules/nx/schemas/nx-schema.json",
"plugins": [
{
"plugin": "@nx-go/nx-go", …
```
=> Add an option to use the plugin without Go installed

.github/workflows/ci.yml, packages/nx-go-e2e/shared/create-test-project.ts, packages/nx-go-e2e/src/nx-go.spec.ts
This pull request includes updates to the CI workflow configuration in the `.github/workflows/ci.yml` file. The changes introduce support for multiple versions of Nx and ensure that the plugin works on a set of Nx versions.
Updates to CI workflow:
* Added `nx_version` matrix to include Nx versions `17.2.8` and `20.1.2`.
* Added a step to set up Nx using the specified version from the matrix.
=> Add integration tests using Nx 20

packages/nx-go-e2e/src/nx-go.spec.ts, packages/nx-go/src/generators/application/generator.spec.ts, packages/nx-go/src/generators/application/generator.ts, packages/nx-go/src/generators/library/generator.spec.ts, packages/nx-go/src/generators/library/generator.ts, packages/nx-go/src/utils/normalize-options.spec.ts, packages/nx-go/src/utils/normalize-options.ts
This pull request adapts the normalization options code to a breaking change in Nx 20.
It's a quick fix to allow generators working on Nx 17-20, but we'll have to clean up and release a version compatible only with Nx 20 soon, to avoid tweaks like this one. In particular, we will need to change default argument from "name" to "directory" to reflect better how Nx 20 works.
> [!NOTE]
> In order to avoid forcing everyone to upgrade to Nx 20 in a hurry, I haven't yet planned to deprecate older versions. The choice will be made in another ticket.
Fixes #145
=> fix: update options normalization for Nx 20 compatibility

docs/executors/serve.md, packages/nx-go/src/executors/serve/executor.spec.ts, packages/nx-go/src/executors/serve/executor.ts, packages/nx-go/src/executors/serve/schema.d.ts, packages/nx-go/src/executors/serve/schema.json
This pull request introduces the ability to pass custom flags to the Go compiler when running a Go application. The changes span documentation updates, schema modifications, and updates to the executor logic and tests.
Closes #77
=> feat: add flags property to serve executor
